import { definePage } from '../../lib/page-types';
import { usd } from '../../lib/kit';
import { FED, exchange1031, federalGainTax } from '../../lib/engine/realestate';

const X = FED.x1031;
// Worked example of the calculator defaults: a rental bought, depreciated, then traded up.
const ex = exchange1031({ salePrice: 800000, costs: 45000, adjustedBasis: 420000, depreciation: 180000, oldDebt: 250000, replacementPrice: 1000000, newDebt: 450000 });
const exTax = federalGainTax({ filing: 'joint', otherTaxable: 180000, ltcg: ex.realized - 180000, unrecaptured: 180000 });
// Boot example: cash taken out and a smaller loan.
const bo = exchange1031({ salePrice: 1000000, costs: 0, adjustedBasis: 400000, depreciation: 100000, oldDebt: 300000, replacementPrice: 900000, newDebt: 260000 });

export default definePage({
  id: '1031-exchange',
  group: 'realestate',
  order: 10,
  slug: '1031-exchange',
  nav: '1031 exchange calculator',
  card: '45 and 180-day rules, boot, deferred gain and the basis you carry forward',
  title: '1031 Exchange 2026: Rules, 45/180-Day Deadlines, Calculator',
  description: `1031 exchange rules for 2026: ${X.identifyDays}-day identification, ${X.exchangeDays}-day closing, like-kind real property, boot and depreciation, with a calculator of the tax deferred.`,
  h1: '1031 exchange: rules and calculator',
  intro: 'Sell an investment property, buy another, and pay the capital gains tax later, if the deadlines and the numbers line up.',
  resume: `A 1031 exchange, named after section 1031 of the Internal Revenue Code, lets the owner of investment or business real estate sell it and put the proceeds into another property without paying tax on the gain that year. Since ${X.realPropertyOnlySince} only real property qualifies, and both properties must be held for investment or for use in a business, never a main home or a house bought to flip. The replacement must be identified in writing within ${X.identifyDays} days of the sale and acquired within ${X.exchangeDays} days, or by the due date of the tax return if that comes first, and the money must sit with a qualified intermediary in between. Any cash you keep and any mortgage that is not replaced is boot, taxed now. In the calculator's example, a rental sold for ${usd(800000)} with a ${usd(ex.realized)} gain and traded up to ${usd(1000000)} defers the whole gain, about ${usd(exTax.federalOnGain + exTax.niit)} of federal tax, and the new property starts with a basis of ${usd(ex.newBasis)}.`,
  tool: 'x1031',
  toolProps: { state: 'florida', price: 800000 },
  fold: true,
  body: (h) => `<h2>The two deadlines that end most failed exchanges</h2>
<p>The clock starts the day the property you give up is transferred, and nothing stops it. By day ${X.identifyDays} you must name the replacement in a signed document delivered to the intermediary or the seller, with a description precise enough to find it: a street address or a legal description. By day ${X.exchangeDays} you must own it. The two periods run at the same time, so the 180 days include the first 45. Weekends and federal holidays count, and the IRS does not extend the dates for a slow lender, except under a disaster relief notice for taxpayers in a declared area.</p>
<p>The 180-day limit has a second edge that catches December sellers. The exchange period ends on the earlier of day 180 or the due date of your return for the year of the sale, extensions included. A rental sold in November reaches day 180 in May, after April 15: file an extension, or the period closes on April 15 even if you have not bought yet. The mini-calculator below gives both dates from your closing day.</p>
<!--mini:exchangeDeadlines-->
<h2>What you may identify</h2>
<p>Most investors use the three-property rule: up to ${X.maxIdentified} potential replacements of any value, and you buy one or more of them. Above three, the total value of everything identified may not exceed twice the price of what you sold (the 200% rule), unless you end up acquiring at least 95% of the value you identified. Identifying a backup is cheap insurance: if the first purchase falls through on day 120, you can still close on property number two. A replacement you did not identify by day 45 cannot be added later.</p>
<h2>Like-kind means real estate for real estate</h2>
<p>The phrase sounds narrow, but for real property it is broad. A duplex can be traded for raw land, a warehouse for a block of condominiums, a farm for a strip mall, and a fee interest for a lease of 30 years or more. What matters is how you hold the property, not what it is: both sides must be held for productive use in a trade or business or for investment. Two exclusions follow. A main home is personal use, covered by the ${h.a('capital-gains-tax-on-home-sale', 'home sale exclusion')} instead. Property bought to fix up and resell quickly is held primarily for sale, which section 1031 shuts out. Real property in the United States and real property abroad are not like-kind, so a rental in Ohio cannot be swapped for an apartment in Lisbon. Equipment, vehicles and artwork stopped qualifying with the 2017 tax law.</p>
<h2>Boot: the part of the deal that is taxed now</h2>
<p>Boot is anything you receive that is not like-kind real estate. Cash left over after the purchase is boot. So is mortgage relief: if the loan paid off on the old property is larger than the loan on the new one, the difference counts as money received, unless you add cash of your own at closing to cover it. Exchange expenses such as the commission and the intermediary fee reduce what you realized. The gain you recognize is the smaller of the boot and the gain itself. Take an owner who sells for ${h.usd(1000000)} with a ${h.usd(300000)} mortgage, buys for ${h.usd(900000)} with a ${h.usd(260000)} loan, and pockets the difference: ${h.usd(bo.cashBoot)} of cash boot plus ${h.usd(bo.debtBoot)} of mortgage boot makes ${h.usd(bo.recognized)} taxable now, and ${h.usd(bo.deferred)} stays deferred.</p>
<!--mini:exchangeBoot-->
<h2>Depreciation recapture rides along</h2>
<p>Depreciation lowered your taxable rental income every year, and it lowered your basis by the same amount. When gain is recognized on residential or commercial buildings, the part that comes from depreciation is unrecaptured section 1250 gain, taxed at your ordinary rate up to a ceiling of ${FED.ltcg.unrecaptured1250MaxPct}%, before the rest of the gain gets the 0%, 15% or 20% capital gains rates. A full exchange defers this too. A partial one does not split it pro rata: the calculator treats recognized boot as recapture first, which is the conservative reading for buildings that have been depreciated on a straight line. The 3.8% net investment income tax applies to recognized gain above $200,000 of income for single filers or $250,000 for couples, thresholds the IRS does not index.</p>
<h2>The intermediary holds the money, not you</h2>
<p>If the sale proceeds reach your bank account, even for a day, the exchange is over. A qualified intermediary, sometimes called an accommodator or facilitator, signs the sale and purchase agreements as the exchanger's assignee and holds the cash in between. Your own attorney, real estate agent, accountant or employee within the last two years cannot serve, nor can a relative. Intermediaries are not licensed by the federal government; ask how the funds are held (a segregated, qualified escrow or trust account protects you if the intermediary fails), and whether your state regulates them.</p>
<h2>Basis carried into the new property</h2>
<p>An exchange postpones the tax, it does not erase it. The deferred gain is subtracted from the price of the replacement to give its basis, so future depreciation is lower and a future taxable sale picks up both gains. In the example above, the ${h.usd(1000000)} replacement starts with a basis of ${h.usd(ex.newBasis)}. The chain can go on for decades. When an owner dies holding the last property, heirs generally receive a basis stepped up to market value, which is why many investors exchange until the end; see ${h.a('estate-tax-by-state', 'estate tax by state')} for what the estate itself may owe.</p>
<h2>Exchanges with relatives and other traps</h2>
<p>Swapping with a related person, such as a family member or a company you control, is allowed, but if either side sells the property received within ${X.relatedPartyYears} years, the deferred gain becomes taxable in that year. Reverse exchanges, where you buy the replacement before selling, are possible through an exchange accommodation titleholder that parks one property for up to 180 days. A vacation home qualifies only if it is rented out at fair value and your personal use stays within limits set by IRS guidance. Report every exchange on Form 8824 with the return for the year the old property was transferred, even when no gain is recognized.</p>
<h2>The state side of a deferred gain</h2>
<p>States with an income tax generally follow the federal deferral, but some keep track of gain on property located in their territory. Since 2014, California requires an annual information return, form ${h.ext('https://www.ftb.ca.gov/forms/2025/2025-3840-instructions.html', 'FTB 3840')}, from anyone who exchanges California property for property outside the state, so the deferred gain can be taxed when the replacement is finally sold. States without an income tax on capital gains have nothing to defer. The calculator applies the top rate of the state you choose to any boot; adjust the rate in the advanced options if your income sits lower. Transfer taxes are not deferred: the deed still pays the ${h.a('closing-costs-calculator', 'transfer tax of the state and county')}.</p>`,
  faqs: [
    { q: 'Can I do a 1031 exchange on my primary residence?', a: `No. Section 1031 covers only real property held for investment or used in a business. A main home is personal use and gets a different break, the exclusion of up to $250,000 of gain, or $500,000 for married couples, under section 121. A home that was rented out and later lived in, or the reverse, can sometimes use both rules, with limits on the gain that can be excluded.` },
    { q: 'What happens if I miss the 45-day identification deadline?', a: `The exchange fails and the sale becomes an ordinary taxable sale. The intermediary returns the proceeds, usually after the 45th day or at the end of the 180-day period depending on the exchange agreement, and the gain is reported in the year the funds are received. There is no grace period; only a federal disaster declaration covering your area can postpone the dates.` },
    { q: 'Do I have to reinvest all the cash to avoid tax in a 1031 exchange?', a: `To defer all the gain, yes: buy a replacement worth at least the net sale price and reinvest all the equity, keeping debt at the same level or replacing it with cash. Any cash you keep is taxed now, up to the amount of your gain, and so is a drop in mortgage debt that you do not cover with extra cash at closing.` },
    { q: 'How long must I hold a property before or after a 1031 exchange?', a: `The tax code sets no minimum holding period. What counts is intent: the property must be held for investment or business use. Many advisers suggest holding a replacement through at least two tax years so the investment intent is easy to show. The only fixed period is two years for exchanges between related persons.` },
    { q: 'Is a 1031 exchange worth it on a small gain?', a: `Compare the tax deferred with the costs. A qualified intermediary charges a fee, and the deadlines can push you to accept a worse property or price. On a modest gain in a state with no income tax, the federal saving may be a few thousand dollars. The calculator shows the tax a plain sale would cost next to the tax due with the exchange.` },
    { q: 'Can I exchange one rental property for two?', a: `Yes. You can sell one property and acquire several, or sell several and buy one, as long as each property is identified in time and the totals respect the reinvestment rules. With more than three replacements, the 200% value limit on identified properties applies. Each property sold and bought still has to be investment or business real estate.` },
  ],
  related: ['capital-gains-tax-on-home-sale', 'closing-costs-calculator', 'estate-tax-by-state', 'property-tax-calculator'],
  sources: ['irsI8824', 'irsPub544', 'irsTopic409', 'irsNiit', 'rp202532'],
});
