import { defineState } from '../../lib/page-types';
import { st, usd, eff, ptx, rank } from '../../lib/kit';

const s = st('alaska');
const C = s.census, PR = s.property;
const senior = PR.homestead.amount ?? 0;
const optional = 75000;
const home = C.medianValue;
const cap = 0.03;
const ceilingHome = 400000;
const billRank = rank(s, (x) => x.census.medianTax);
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'alaska',
  title: `Alaska Sales Tax 2026: None Statewide, Local Taxes Apply`,
  description: `Alaska sales tax in 2026: no state tax, but boroughs and cities set their own, online orders included. Property tax: median ${usd(C.medianTax)}, ${usd(senior)} senior exemption.`,
  intro: `The state takes nothing at the register, so every sales tax in Alaska is a borough or city decision, and the same holds for the property tax bill.`,
  resume: `Alaska has no statewide sales tax and no state use tax. That does not make every purchase tax free: state law lets boroughs and cities levy their own sales and use taxes, on goods and also on rents and services, and each sets its rate, its exemptions and any cap per sale by ordinance, with no statutory maximum. Where no local tax exists the rate is 0%, so the tax depends on the delivery address alone. Since February 2020, online sellers collect those local taxes for member jurisdictions of the Alaska Remote Seller Sales Tax Commission. Property tax is also purely local, and heavier than the missing sales tax suggests: the median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51 by rate and ${billRank} by median bill. Seniors and disabled veterans get the first ${usd(senior)} of value exempt.`,
  sales: (h) => `<p>There is no Alaska rate to look up, only local ones. Two sections of the municipal code carry the whole system: AS 29.45.650 lets a borough tax sales, rents and services, and AS 29.45.700 lets a city levy a sales tax inside or outside a borough. A borough or city that taxes sales may add a use tax at the same rate, with credit for sales tax paid elsewhere. Exemptions follow the same pattern. Food, clothing and medicine are free of state tax only because there is no state tax; whether the local ordinance exempts them is a separate question for each community, and the answer changes from one town to the next. One rule binds them all: anything paid for with SNAP or WIC benefits cannot be taxed by a borough or a city.</p>
<p>Online orders are caught by the same local taxes. Since February 2020, the Alaska Remote Seller Sales Tax Commission, a body formed by the municipalities themselves rather than a state agency, collects local tax on remote sales for its member jurisdictions, sourced to the point of delivery. Sellers must register once their sales into Alaska pass ${h.usd(100000)} a year; the old 200-transaction test was dropped on January 1, 2025.</p>
<p>The weak point is the ZIP code. Many Alaska ZIP codes cover far more ground than any taxing boundary, so a cabin outside a taxing area can be billed as if it sat in town. The Commission's official tax map shows whether an address falls inside a taxing jurisdiction, and its refund form recovers tax charged by mistake. Check the map, then enter the local rate in the calculator above; outside a taxing area, leave it at zero. Late municipal sales tax cannot carry interest above 15% a year.</p>`,
  property: (h) => `<p>Most Alaskans who pay property tax pay it to a borough, a city, or both, and many areas of the state levy none. The state's own property tax is narrow: 20 mills on oil and gas production and pipeline property under AS 43.56, with a credit for local tax paid on the same property. Homes are valued at full and true value as of January 1, meaning the price a willing buyer would pay a willing seller on the open market.</p>
<p>Two state limits restrain local levies. A municipality may not tax more than 30 mills, 3% of assessed value, in a year, so a ${h.usd(ceilingHome)} house can never owe a single municipality more than ${h.usd(ceilingHome * cap)}. Total municipal tax revenue is also capped at $1,500 per resident a year. Actual bills sit well under the ceiling: at the Census ratio of ${h.eff(C.effectiveRate)}, the median ${h.usd(home)} home pays about ${h.usd(ptx('alaska', home))}.</p>
<p>The one exemption written into state law is generous. Residents aged 65 or older, disabled veterans and surviving spouses aged 60 or more have the first ${h.usd(senior)} of their primary residence's assessed value exempt. On the median home, that would leave ${h.usd(home - senior)} taxable, or roughly ${h.usd(ptx('alaska', home - senior))} at the typical ratio. A municipality may require seniors to be eligible for the Permanent Fund Dividend before granting it. With voter approval, a borough or city can also exempt up to ${h.usd(optional)} of value on every residence, and one vehicle per household owned by a resident aged 65 or older escapes property or registration tax. Applications go in writing to the local assessor, and deadlines and payment dates are set by each municipality.</p>`,
  faqs: [
    { q: 'Why was I charged sales tax on an online order to Alaska?', a: `Because the delivery address sits in a borough or city that levies a local sales tax and belongs to the Alaska Remote Seller Sales Tax Commission, which has collected local tax on remote sales since February 2020. If your address is outside any taxing area, a ZIP code covering several jurisdictions may have misled the seller: the Commission's tax map confirms the status of your address, and its refund form returns tax charged in error.` },
    { q: 'Do seniors pay property tax in Alaska?', a: `They pay less. State law exempts the first ${usd(senior)} of assessed value on the primary residence of a resident aged 65 or older, a disabled veteran, or a surviving spouse aged 60 or more. Value above that is taxed normally, and a municipality may require eligibility for the Permanent Fund Dividend. Apply in writing to the local assessor before the municipality's deadline.` },
    { q: 'Is there a limit on property tax rates in Alaska?', a: `Yes. A borough or city may not levy more than 30 mills, or 3% of assessed value, in a year, and its total tax revenue may not exceed $1,500 per resident a year. Property is valued at full market value as of January 1. In practice the typical effective rate is far lower, ${eff(C.effectiveRate)} of value in the 2024 Census figures.` },
  ],
  related: ['washington', 'hawaii', 'oregon', 'montana', 'states-without-sales-tax', 'homestead-exemption-by-state'],
});
