import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank, day, dayShort } from '../../lib/kit';

const s = st('florida');
const S = s.sales, C = s.census, PR = s.property;
const school = S.holidays2026?.[0];
const outdoors = S.holidays2026?.[1];
const surtaxBase = 5000;
const topSurtax = 2;
const boat = 42000;
const laptop = tx('florida', 1300);
const hs = PR.homestead.amount ?? 0;
const sohValue = 320000;
const bill = 4200;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'florida',
  title: `Florida Sales Tax 2026: ${rate(S.stateRate)} Rate, County Surtax Capped`,
  description: `Florida sales tax in 2026: ${rate(S.stateRate)} state rate, county surtax only on the first $5,000 of an item, a month-long school holiday, and a ${usd(hs)} homestead exemption.`,
  intro: `One state rate everywhere in Florida, a county surtax that stops at the first $5,000 of anything you buy, and homestead rules that reward staying put.`,
  resume: `Florida charges a ${rate(S.stateRate)} state sales tax, and most counties add a discretionary sales surtax, currently between 0.5% and 2%, for infrastructure, schools or transportation. The surtax has a rare limit: it applies only to the first $5,000 of the price of a single item of tangible personal property, so on a car, a boat or an expensive appliance the county part stops early. Groceries and prescription drugs are exempt; clothing is taxed except during the back-to-school holiday, which since 2026 runs every year from July 20 to August 20. Since August 1, 2025, disaster-preparedness items such as batteries, carbon monoxide alarms and fire extinguishers are exempt all year. On property, the median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51. A homestead exemption of up to ${usd(hs)} and the Save Our Homes cap, 3% a year or inflation if lower, shape what a resident owner actually pays.`,
  sales: (h) => `<p>The ${h.usd(surtaxBase)} rule is the first thing to understand about Florida's county surtax. A ${h.usd(boat)} boat delivered in a county with the highest surtax, 2%, pays the full ${h.rate(S.stateRate)} state tax on the whole price, ${h.usd(boat * S.stateRate / 100)}, but county surtax of only ${h.usd(surtaxBase * topSurtax / 100)}. The limit covers goods, not services, admissions or short-term rentals. For cars and mobile homes, the surtax of the buyer's home county applies, not that of the dealer. The Department of Revenue's address lookup returns the surtax for any location.</p>
<p>The holiday calendar changed in 2026. Chapter 2026-239, Laws of Florida, moved the back-to-school holiday to a fixed window, ${school ? `${dayShort(school.start)} to ${h.day(school.end)}` : 'July 20 to August 20'}, after an August-long edition in 2025. It covers clothing, shoes, wallets and bags up to $100, school supplies up to $50, learning aids up to $30, and personal computers up to $1,500, so a ${h.usd(1300)} laptop saves ${h.usd(laptop.stateTax, 2)} of state tax plus the surtax. Dealers cannot opt out. A second holiday for hunting, fishing and camping gear runs ${outdoors ? `from ${dayShort(outdoors.start)} to ${h.day(outdoors.end)}` : 'in the fall'}.</p>
<p>Several permanent exemptions are recent. Florida ended its sales tax on commercial rent for periods beginning on or after October 1, 2025, a tax no other state levied. Impact-resistant windows, doors and garage doors installed on eligible homes are exempt from July 1, 2026 through June 30, 2029, and gold and silver coins recognized as legal tender since July 1, 2026. SB 1074, signed in May 2026, lets stores round in-person cash sales to the nearest nickel. Online purchases made without Florida tax owe use tax at ${h.rate(S.stateRate)} plus the delivery county's surtax.</p>`,
  property: (h) => `<p>Florida has no state property tax on real estate. Counties, cities, school districts and special districts levy millage; the county property appraiser sets values and exemptions as of January 1, and the county tax collector sends the bill in November. Paying early is rewarded: 4% off in November, 3% in December, 2% in January and 1% in February, so a ${h.usd(bill)} bill paid in November costs ${h.usd(bill * 0.96)}. Taxes become delinquent on April 1, and the county sells tax certificates on unpaid bills by June 1.</p>
<p>The homestead exemption works in two tiers. The first $25,000 of assessed value is exempt from every levy, school taxes included. A second exemption of up to $25,000 covers value between $50,000 and $75,000, for non-school levies only, and is indexed to inflation each January. The Department of Revenue's own example uses a home assessed at ${h.usd(65000)}: the first ${h.usd(25000)} is exempt, the next ${h.usd(25000)} is taxable, and the last ${h.usd(15000)} escapes non-school taxes. File Form DR-501 with the property appraiser by March 1; you must own and live in the home on January 1.</p>
<p>Save Our Homes matters more over time. After the first homestead year, the assessed value can rise by no more than 3% or the change in the CPI, whichever is lower, even in a year when market value falls. A homestead assessed at ${h.usd(sohValue)} can reach at most ${h.usd(sohValue * 1.03)} the next year. The gap between market and assessed value can be carried to a new Florida homestead, in whole or in part, if it is established within three years (Form DR-501T, by March 1). At the Census ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(400000)} home pays about ${h.usd(ptx('florida', 400000))} a year; counties and cities may add an extra exemption of up to $50,000 for low-income owners aged 65 or older.</p>`,
  faqs: [
    { q: 'Does Florida charge sales tax on the full price of a car?', a: `The ${rate(S.stateRate)} state tax applies to the full price, but the county discretionary surtax applies only to the first ${usd(surtaxBase)}. At the highest surtax of 2%, the county part can never exceed ${usd(surtaxBase * topSurtax / 100)} on one vehicle. For cars, the surtax of the county where the buyer lives applies, wherever the dealer is located in Florida.` },
    { q: 'When is the Florida back-to-school tax holiday in 2026?', a: `From July 20 to August 20, 2026, and on the same dates every year since Chapter 2026-239 fixed the window. Clothing, shoes, wallets and bags up to $100 an item, school supplies up to $50, learning aids up to $30 and personal computers up to $1,500 for personal use are exempt from state tax and county surtax. Dealers cannot opt out.` },
    { q: 'How does Save Our Homes portability work in Florida?', a: `When you sell a Florida homestead and set up a new one, you can transfer all or part of the difference between the old home's market and assessed values, built up under the Save Our Homes cap. The new homestead must be established within three years of January 1 of the year you left the old one. File Form DR-501T with the property appraiser by March 1.` },
  ],
  related: ['georgia', 'alabama', 'sales-tax-holidays', 'homestead-exemption-by-state', 'property-tax-assessment-caps'],
});
