import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank } from '../../lib/kit';

const s = st('idaho');
const S = s.sales, C = s.census;
const week = tx('idaho', 150, 'groceries');
const effRank = rank(s, (x) => x.census.effectiveRate);
const halfCap = 125000;
const home = C.medianValue;
const exemptMedian = Math.min(home / 2, halfCap);

export default defineState({
  slug: 'idaho',
  title: `Idaho Sales Tax 2026: ${rate(S.stateRate)} on Food Too, Property Tax ${eff(C.effectiveRate)}`,
  description: `Idaho sales tax in 2026: ${rate(S.stateRate)} statewide, groceries taxed with a food tax credit, resort city taxes, and property tax with the homeowner's 50% exemption.`,
  intro: `One rate almost everywhere, groceries taxed at the register and partly refunded on the income tax return, and one of the lighter property tax burdens in the West.`,
  resume: `Idaho charges ${rate(S.stateRate)} sales tax and the same ${rate(S.stateRate)} use tax, and outside a couple of dozen resort cities that is the whole rate. Unlike most states, Idaho does not exempt groceries: food is taxed at the full rate, so a ${usd(150)} weekly shop carries ${usd(week.stateTax, 2)} of tax, and the state gives part of it back through the food tax credit on the income tax return, ${usd(155)} per resident and per qualifying dependent for 2025. Clothing is taxed like other goods; prescription drugs are exempt. The resort cities, from Ketchum and Sun Valley to McCall and Sandpoint, set their own voter-approved local option tax, sometimes only on lodging, drinks and restaurant meals. On property, the typical owner paid ${usd(C.medianTax)} on a median home of ${usd(C.medianValue)}, an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51, helped by a homeowner's exemption that halves the taxable value of a primary residence.`,
  sales: (h) => `<p>Idaho's sales tax has stayed simple since it was adopted in 1965: one state rate of ${h.rate(S.stateRate)}, applied to retail sales of goods, short-term lodging, meals, admissions and digital goods bought to keep. What makes the Idaho receipt different from its neighbors' is the grocery line. Bread, produce and milk are taxed at the same ${h.rate(S.stateRate)} as a television, and the state compensates households after the fact instead of at the checkout. The food tax credit (it used to be called the grocery credit) is claimed on the Idaho income tax return; residents who earn too little to file can still claim the refund, and those who keep receipts can receive more. For tax year 2024, more than 101,000 non-filers did so, according to the Tax Commission.</p>
<p>Local taxes are the exception rather than the rule. Only resort cities may add a local option sales tax, after a vote of their residents, and the Tax Commission lists twenty-three of them, among them Ketchum, Hailey, Driggs, Stanley and Bonners Ferry. Each decides what its tax covers: everything the state taxes, or only rooms, alcohol by the drink and restaurant food. A few areas also have an auditorium district tax. Idaho does not publish an address lookup, so if you shop or stay in one of those towns, ask the city for its rate and type it into the calculator; everywhere else, leave the local field at zero.</p>
<p>Two details matter at the counter. Separately stated delivery charges and installation or repair labor are not taxable, while parts used in a repair are. And a trade-in lowers the taxable price: the Tax Commission's own example taxes an ${h.usd(800)} range on ${h.usd(550)} after a ${h.usd(250)} trade-in.</p>`,
  property: (h) => `<p>In Idaho, local districts levy the property tax (counties, cities, school districts, highway and other special districts), county assessors set the values and county treasurers collect. Every property is assessed at its full market value as of January 1, with no fractional assessment ratio, which makes Idaho bills easy to rebuild: taxable value times the combined levy of your districts. Growth is limited at the budget level rather than on each home: a taxing district may raise its property tax budget by only 3% a year, plus new construction and annexation, unless voters approve more.</p>
<p>The homeowner's exemption is the main relief. It takes half of the value of an owner-occupied primary residence, with up to one acre of land, off the taxable value, up to a reduction of ${h.usd(halfCap)}. On the median Idaho home of ${h.usd(home)}, that means ${h.usd(exemptMedian)} off. You apply once with the county assessor, by April 15 for the current year, and it renews while you qualify. Owners with low household income who are seniors, disabled or in other listed groups can add the Circuit Breaker, worth up to ${h.usd(1500)} a year, but that one must be applied for every year. At the typical statewide rate, a ${h.usd(500000)} house pays about ${h.usd(ptx('idaho', 500000))} a year; bills are payable in two halves, on December 20 and June 20.</p>`,
  faqs: [
    { q: 'Does Idaho charge sales tax on groceries in 2026?', a: `Yes. Idaho taxes food at the full ${rate(S.stateRate)} state rate, one of the few states that still do. To offset it, residents claim the food tax credit on the Idaho income tax return, ${usd(155)} per person for 2025, and residents who do not need to file can still request the refund, up to ${usd(250)} with receipts.` },
    { q: 'Which Idaho cities add a local sales tax?', a: `Only resort cities may add a local option sales tax, approved by their voters. The Idaho State Tax Commission lists twenty-three, including Ketchum, Sun Valley, Hailey, McCall, Sandpoint, Driggs and Stanley. Each city chooses whether the tax covers all taxable sales or only lodging, alcohol by the drink and restaurant food, so ask the city for its rate.` },
    { q: 'How much does the Idaho homeowner’s exemption save?', a: `It removes half of the taxable value of your primary residence and up to one acre, capped at a ${usd(halfCap)} reduction. On a ${usd(400000)} home, ${usd(halfCap)} comes off before your districts' levies apply. Apply to your county assessor by April 15; the exemption then renews automatically while you own and live in the home.` },
  ],
  related: ['montana', 'washington', 'utah', 'oregon', 'grocery-sales-tax-by-state', 'homestead-exemption-by-state'],
});
