import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, ptx, rank } from '../../lib/kit';

const s = st('montana');
const S = s.sales, C = s.census, L = s.sales.local;
const lodging = S.otherRates?.[0]?.rate ?? 0;
const car = S.otherRates?.[1]?.rate ?? 0;
const cap = L.cap ?? 0;
const night = 180, nights = 4, rental = 350;
const stay = night * nights;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'montana',
  title: `Montana Sales Tax 2026: None Statewide, ${rate(cap)} Resort Tax Cap`,
  description: `Montana sales tax in 2026: no general sales tax, but an ${rate(lodging)} lodging tax, ${rate(car)} on car rentals and resort taxes up to ${rate(cap)}. Property tax: a median bill of ${usd(C.medianTax)}.`,
  intro: `No sales tax at the checkout counter, but hotel rooms, rental cars and a handful of tourist towns are a different story.`,
  resume: `Montana has no general sales tax, so groceries, clothing, cars bought from a dealer and online orders delivered to a Montana address carry no state sales tax, and there is no use tax to report either. What replaces it is narrow and aimed mostly at visitors: a combined ${rate(lodging)} lodging facility tax on hotels, motels, campgrounds and short-term rentals, a ${rate(car)} tax on vehicles rented for under 30 days, and a voter-approved resort tax of up to ${rate(cap)} in a few small tourism towns such as Big Sky, West Yellowstone, Whitefish and Red Lodge. Property tax carries the weight instead. The median owner paid ${usd(C.medianTax)} in 2024 on a home worth ${usd(C.medianValue)} (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51. Since 2026 a primary residence enrolled for the Homestead Reduced Tax Rate is taxed on tiered rates instead of the flat 1.90% charged on second homes and short-term rentals.`,
  sales: (h) => `<p>A Montanan can buy a ${h.usd(1200)} laptop, a winter coat or a week of groceries and pay exactly the sticker price. The Department of Revenue states it plainly: there is no general sales tax, no sales tax exemption certificate and no consumer use tax, which also means a Montana resident cannot deduct another state's sales tax on the Montana income tax return. Shopping across a state line follows that state's rules for nonresidents, not Montana's.</p>
<p>Three taxes fill part of the gap, and all three land on travel. Lodging is the big one: ${h.rate(lodging)}, made of a 4% lodging sales tax and a 4% lodging facility use tax, on hotel rooms, campgrounds and vacation rentals, including bookings made through short-term rental platforms, which have had to register and collect since Senate Bill 52. Four nights at ${h.usd(night)} add ${h.usd(stay * lodging / 100)} to a ${h.usd(stay)} stay; stays of 30 days or more are exempt. Renting a car for a week at ${h.usd(rental)} adds ${h.usd(rental * car / 100, 2)} under the ${h.rate(car)} rental vehicle tax.</p>
<p>The third piece is local and rare. Communities designated by the Department of Commerce, with fewer than 5,500 residents (2,500 for an unincorporated area) and an economy built on tourism, may ask voters for a resort tax of up to ${h.rate(cap)}. It covers lodging, restaurant meals, bars, ski areas and goods classed as luxuries sold in the area, and at least 5% of the money must offset local property taxes. The Department of Revenue does not run it and has no address lookup, so a skier in Big Sky should read the receipt, or ask the town, before typing a local rate into the calculator above.</p>`,
  property: (h) => `<p>Montana builds the bill in two steps. The Department of Revenue appraises every home at market value and revalues residential land every two years. The Legislature then sets a tax rate, a percentage, that turns market value into taxable value, and the county, city, school district and other local levies apply their mills to that taxable value. Because local budgets are capped by state law, the mills move the opposite way from values: when taxable value climbs, fewer mills are needed to raise the same budget.</p>
<p>The 2025 Legislature rewrote the residential rates with HB 231 and SB 542. For 2026, an enrolled primary residence or long-term rental is taxed at 0.76% on the first $378,000 of market value, 0.90% up to $756,000, 1.10% up to $1,511,999 and 1.90% above $1,512,000, while a second home, a short-term rental or an empty residential lot pays a flat 1.90% on its whole value. For a ${h.usd(500000)} house that is used as a cabin rather than a residence, the difference in taxable value is large enough to show up in every mill.</p>
<p>At the Census median ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(400000)} home pays about ${h.usd(ptx('montana', 400000))} a year. To keep the reduced rate, the owner must live in the home at least seven months a year, be current on taxes and enroll with the Department of Revenue at homestead.mt.gov; owners who took the 2025 rebate in the same home were enrolled automatically. A buyer whose home was not enrolled for 2026 pays at 1.90% and can claim the difference back between January 1 and May 31, 2027. Bills come in two halves, due November 30 and May 31, or in seven monthly payments for a primary residence.</p>`,
  faqs: [
    { q: 'Do Montana hotels charge sales tax?', a: `Yes. Montana has no general sales tax, but hotels, motels, campgrounds and vacation rentals collect a combined ${rate(lodging)} lodging facility tax: a 4% lodging sales tax plus a 4% use tax. Short-term rental platforms collect it too. Stays of 30 continuous days or more are exempt, and a designated resort town such as West Yellowstone or Big Sky can add its own resort tax of up to ${rate(cap)}.` },
    { q: 'How do I apply for the Montana homestead reduced tax rate?', a: `Enroll online with the Montana Department of Revenue at homestead.mt.gov. For the 2027 tax year, the window runs from May 4, 2026 to March 1, 2027. The home must be your principal residence for at least seven months a year and taxes must be current. Without enrollment, the home is taxed at the flat 1.90% rate used for second homes instead of the tiered rate starting at 0.76%.` },
    { q: 'Do I owe tax on online orders shipped to Montana?', a: `No. Because Montana has no general sales tax, it also has no general use tax, and the Wayfair ruling that lets states make remote sellers collect does not create a tax for Montana buyers. An order delivered to a Montana address should arrive with no sales tax. The exceptions are lodging, short-term vehicle rentals and purchases inside a resort area that levies its own tax.` },
  ],
  related: ['idaho', 'wyoming', 'north-dakota', 'states-without-sales-tax', 'property-tax-assessment-caps'],
});
