import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank } from '../../lib/kit';

const s = st('nebraska');
const S = s.sales, C = s.census, L = s.sales.local;
const cap = L.cap ?? 0;
const lodging = S.otherRates?.[0]?.rate ?? 0;
const tv = tx('nebraska', 800);
const tvSSC = tx('nebraska', 800, 'general', 1.5);
const tvHomer = tx('nebraska', 800, 'general', 0.5);
const credit = 118.87 * 3;
const billRank = rank(s, (x) => x.census.medianTax);

export default defineState({
  slug: 'nebraska',
  title: `Nebraska Sales Tax 2026: ${rate(S.stateRate)} Rate, Candy Exempt, Credits`,
  description: `Nebraska sales tax in 2026: ${rate(S.stateRate)} state rate, local add-ons up to ${rate(cap)}, candy and soda exempt, Good Life Districts, and state credits on a ${usd(C.medianTax)} median bill.`,
  intro: `A grocery exemption that even covers candy and soda, local rates that can only change four times a year, and a property tax bill the state now pays part of.`,
  resume: `Nebraska charges a ${rate(S.stateRate)} state sales tax, and cities, villages and counties may add a voter-approved local rate of up to ${rate(cap)}, so combined rates on the Department of Revenue's rate cards run up to 7.5%. The grocery exemption is wider than in most states: food for home consumption is exempt, and so are soft drinks, candy, chewing gum and bottled water, while restaurant meals, vending machine food, alcohol and dietary supplements are taxed. Clothing has no exemption. Goods shipped to a buyer are taxed at the rate of the delivery address. Property tax is the heavier load: Nebraska ranks ${billRank} of 51 for the median bill, ${usd(C.medianTax)} a year on a ${usd(C.medianValue)} home (Census ACS 2024), an effective rate of ${eff(C.effectiveRate)}. Two state-funded credits now come off every tax statement, and owners aged 65 and over with modest incomes can file Form 458 for the homestead exemption.`,
  sales: (h) => `<p>The local layer in Nebraska is easy to read once you know who can levy it. A city or village may adopt 0.5%, 1%, 1.5%, 1.75% or ${h.rate(cap)}; a county may too, but only Dakota County does, and its 0.5% applies only outside towns that already have their own tax. The Department of Revenue uses that county as its textbook case: an ${h.usd(800)} television bought in Homer carries ${h.usd(tvHomer.tax, 2)} of tax, while the same set bought in South Sioux City, with its 1.5% city rate and no county rate, carries ${h.usd(tvSSC.tax, 2)}. With no local tax at all, the state part alone is ${h.usd(tv.stateTax, 2)}. Any new local rate, increase or repeal starts only on January 1, April 1, July 1 or October 1, at least 120 days after the ordinance reaches the Department.</p>
<p>Good Life Districts are the Nebraska oddity: inside them, special state-rate rules apply. LB 707, passed in 2025, put most of them back on the full ${h.rate(S.stateRate)} on October 1, 2025, and cancelled the 2.75% district option tax planned for Avenue One and Nebraska Crossing. Retailers that opt in inside GLD Avenue One in Omaha still charge a 2.75% state rate, so a receipt there can look lower than the rest of the metro.</p>
<p>Other rules worth knowing before you shop: hotels add a ${h.rate(lodging)} state lodging tax on top of sales tax; repair labor on a worn car part is not taxed, but installing new parts or painting a car is; and since 2025 gold, silver, platinum and palladium bullion is exempt. LB 901 removed several business exemptions on July 1, 2026. Orders from sellers who did not charge Nebraska tax owe use tax, reported on Form 1040N or Form 3.</p>`,
  property: (h) => `<p>County assessors value homes at 100% of market value as of January 1, and agricultural land at 75%. Values are set by March 19, notices of change go out by June 1, and an owner who disagrees has from June 1 to June 30 to protest to the county board of equalization. Counties, cities, school districts, natural resources districts, community colleges and other bodies then set their levies,.</p>
<p>What makes the Nebraska statement unusual is the state money printed on it. The Real Property Tax Credit pays $118.87 per $100,000 of taxable value on homes and other non-farm property for 2026, about ${h.usd(credit, 2)} on a house assessed at ${h.usd(300000)}. The larger School District Property Tax Relief Credit, created by LB 34 in the 2024 special session, cuts each parcel's school taxes in proportion to what the district levies, with $809,538,045 set aside for 2026-2027. It replaced the old refundable income tax credit, which ended after tax year 2023, so owners no longer claim it on their income tax return.</p>
<p>At the Census ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(250000)} home pays roughly ${h.usd(ptx('nebraska', 250000))} a year before those credits are counted against specific levies. Growth in what cities, villages and counties may request is capped by the Property Tax Growth Limitation Act, and from January 1, 2027, LB 803 requires a two-thirds board vote to raise a request above the prior year's. Owners 65 or older can get full relief from the homestead exemption with income up to $37,000.99 single or $43,400.99 married, provided they live in the home from January 1 through August 15. The exemption shrinks 10% for each $2,500 the home's value exceeds the county maximum.</p>`,
  faqs: [
    { q: 'Is candy taxed in Nebraska?', a: `No. Nebraska's food exemption covers food and food ingredients for home consumption, and the Department of Revenue's regulation puts candy, chewing gum, soft drinks and bottled water inside it, which many states do not. What remains taxable at ${rate(S.stateRate)} plus any local rate is prepared food, food sold through vending machines, alcoholic beverages and dietary supplements. Local sales taxes follow the same food exemption.` },
    { q: 'When is the Nebraska homestead exemption deadline?', a: `For 2026, file Form 458, with Schedule I for income, at your county assessor's office between February 2 and June 30, 2026; a county board may extend the deadline to July 20. You must own and occupy the home from January 1 through August 15. Owners 65 or older qualify on income and home value, and veterans with a 100% permanent service-connected disability have no income or value limit.` },
    { q: 'Why is the sales tax lower at some stores in Omaha?', a: `Retailers inside GLD Avenue One, a Good Life District in Omaha, can opt in to a 2.75% state rate instead of the regular ${rate(S.stateRate)}, plus any local rate. LB 707 returned most other Good Life Districts to the full rate on October 1, 2025, and cancelled a planned district option tax, so outside Avenue One the normal state and local rates apply.` },
  ],
  related: ['iowa', 'kansas', 'south-dakota', 'colorado', 'grocery-sales-tax-by-state', 'property-tax-by-state'],
});
