import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank } from '../../lib/kit';

const s = st('new-york');
const S = s.sales, C = s.census;
const coat = tx('new-york', 120, 'clothing');
const shirt = tx('new-york', 95, 'clothing');
const T = S.clothing.threshold ?? 0;
const nyRank = rank(s, (x) => x.census.medianTax);

export default defineState({
  slug: 'new-york',
  title: `New York Sales Tax 2026: ${rate(S.stateRate)} State Rate, STAR, Property Tax`,
  description: `New York sales tax in 2026: the ${rate(S.stateRate)} state rate plus county and city taxes, the ${usd(T)} clothing rule, food exemptions, and property tax with STAR (median ${usd(C.medianTax)}).`,
  intro: `A ${rate(S.stateRate)} state rate that almost nobody pays alone, a clothing exemption that depends on the county, and some of the highest property tax bills in the country.`,
  resume: `New York charges a ${rate(S.stateRate)} state sales tax, but every county and several cities add their own rate, and sales inside the Metropolitan Commuter Transportation District carry an extra 0.375%, so the rate at the register is the state part plus a local part that depends on where the goods are delivered. Food sold by grocery stores is exempt, while candy, prepared food and heated food are taxed. Clothing and footwear under ${usd(T)} an item escape the state tax, but the county or city part still applies unless that locality has chosen to exempt them too: a ${usd(95)} shirt owes ${usd(shirt.stateTax, 2)} of state tax and a ${usd(120)} coat owes ${usd(coat.stateTax, 2)}. On property, New York ranks ${nyRank} of 51 for the median bill, ${usd(C.medianTax)} a year on a median home of ${usd(C.medianValue)} (Census ACS 2024), and the STAR program is the main relief for owner-occupants.`,
  sales: (h) => `<p>The structure is simple to describe and hard to memorise. The state takes ${h.rate(S.stateRate)} on taxable sales everywhere; every county, New York City itself and several other cities set their own local rate on top; and in the Metropolitan Commuter Transportation District around the city, a 0.375% surcharge is added again. Because New York taxes at the point of delivery, a laptop shipped to an apartment in Brooklyn and the same laptop shipped to a cabin in the Adirondacks are taxed at different combined rates even when the seller is the same. The Tax Department's own rate page lists every locality and links the address lookup, which is the only reliable way to get the local part right.</p>
<p>Two rules trip up visitors more than the rate itself. The first is the clothing threshold, which works per item, not per receipt: five shirts at ${h.usd(38)} each are all under the limit, even though the bill is ${h.usd(190)}. At ${h.usd(T)} and above, the whole price is taxed, not just the part above the limit, unlike Massachusetts or Rhode Island. The second is food: groceries are exempt, but a hot rotisserie chicken, a sandwich made to order or anything eaten in the store is taxed like a restaurant meal. Choose “Clothing” or “Groceries” in the calculator above to see the rule applied to your amount, and type your county's local rate if you know it.</p>`,
  property: (h) => `<p>The state of New York does not collect property tax at all. Counties, cities, towns, villages, school districts and special districts levy it, and school districts take the largest share. Assessments are local too: a town can assess at full market value or at a uniform fraction of it, so a bill that says ${h.usd(27000)} of assessed value may describe a ${h.usd(100000)} house in a town assessing at 27%. That is why comparing mill rates between two New York towns tells you little until you also compare their levels of assessment.</p>
<p>At the median, owners paid ${h.usd(C.medianTax)} a year, ${h.eff(C.effectiveRate)} of the home's value. On a ${h.usd(400000)} house that typical rate gives about ${h.usd(ptx('new-york', 400000))}, though Long Island, Westchester and the suburbs of upstate cities sit well above it and New York City's own property tax classes work differently. STAR, the School Tax Relief program, reduces the school portion of the bill for owner-occupied primary residences; new homeowners now receive it as a credit check from the Tax Department rather than as an exemption on the bill, and they must register for it. Seniors can also qualify for Enhanced STAR and, where the locality offers it, for the senior citizens exemption, which can cut the taxable assessment by up to half.</p>`,
  faqs: [
    { q: 'Do I pay New York sales tax on a $100 pair of sneakers?', a: `Not the state part: footwear sold for less than ${usd(T)} a pair is exempt from New York's ${rate(S.stateRate)} state tax. Whether you pay the local part depends on the county or city where you take delivery, because each locality chooses whether to extend the exemption to its own rate, and may change that choice only on March 1. The Tax Department's clothing bulletin lists the localities that exempt it.` },
    { q: 'Why is the sales tax different in Manhattan and in Buffalo?', a: `Both pay the same ${rate(S.stateRate)} state rate, but New York City and Erie County set different local rates, and Manhattan also sits inside the Metropolitan Commuter Transportation District, which adds 0.375%. Buffalo is outside that district. Because New York taxes at the point of delivery, the address where you receive the goods decides which local rate applies.` },
    { q: 'How do I get STAR if I just bought a house in New York?', a: `New homeowners register with the New York State Tax Department for the STAR credit; the older STAR exemption on the tax bill is closed to new applicants. You must own and live in the home as your primary residence, and household income must be within the limit for the Basic or Enhanced credit. The credit then arrives as a check or direct deposit before school taxes are due.` },
  ],
  related: ['new-jersey', 'connecticut', 'pennsylvania', 'clothing-sales-tax-by-state', 'homestead-exemption-by-state', 'local-sales-tax-rates'],
});
