import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank, day, dayShort } from '../../lib/kit';

const s = st('new-mexico');
const S = s.sales, C = s.census;
const hol = S.holidays2026?.[0];
const car = S.otherRates?.[0]?.rate ?? 0;
const repair = tx('new-mexico', 500);
const laptop = tx('new-mexico', 900);
const value = 300000;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'new-mexico',
  title: `New Mexico Sales Tax 2026: ${rate(S.stateRate)} GRT, Services Taxed Too`,
  description: `New Mexico sales tax in 2026 is a ${rate(S.stateRate)} gross receipts tax on goods and most services, local add-ons, a summer holiday, and property tax at ${eff(C.effectiveRate)} of value.`,
  intro: `What looks like a sales tax on the receipt is a tax on the seller's gross receipts, and it reaches the plumber and the mechanic as well as the store.`,
  resume: `New Mexico does not have a sales tax in the strict sense: it has a gross receipts tax, or GRT, owed by the seller on its receipts and usually passed on to the buyer as a separate line on the invoice. The state part has been ${rate(S.stateRate)} since July 1, 2023, and counties and municipalities add local option increments, so the combined rate depends on the location of the sale. Unlike most sales taxes, GRT covers most services as well as goods, from car repairs to professional fees. Food sold by SNAP-certified grocery stores and prescription drugs are deductible, clothing is taxed except during the back-to-school holiday, and cars pay a separate motor vehicle excise tax instead. Property tax is low: the median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51, helped by a 33 1/3% assessment ratio and a 3% yearly cap on residential value increases.`,
  sales: (h) => `<p>The legal difference matters in practice. Because the gross receipts tax falls on the business, the Taxation and Revenue Department treats it as part of the seller's receipts, and when the seller passes it on it must show it separately on the invoice. The broad base is the bigger surprise for newcomers: a ${h.usd(500)} plumbing repair owes ${h.usd(repair.stateTax, 2)} of state GRT before any local increment, just like a ${h.usd(500)} microwave. Remote sellers and marketplaces collect it once they pass $100,000 of taxable New Mexico receipts in the previous calendar year.</p>
<p>Local increments are set by county commissions and municipal councils, collected by the state and paid back to them. Since July 1, 2025, they can change only in July, save for emergencies such as a natural disaster, so a rate looked up in July normally holds until the next July. The July 2026 schedule raised local rates in Los Ranchos de Albuquerque and much of Colfax County, including Raton, Angel Fire and Cimarron. Look up the location code on the department's map and enter the local part in the calculator above.</p>
<p>The ${hol ? `${dayShort(hol.start)} to ${h.day(hol.end)}` : 'annual'} back-to-school holiday runs from the last Friday in July to the following Sunday, as set by Section 7-9-95. It covers clothing and shoes under $100 an item, computers and e-readers up to $1,000, related peripherals up to $500 and school supplies under $30, with backpacks up to $100 and calculators up to $200. A ${h.usd(900)} laptop bought that weekend saves ${h.usd(laptop.stateTax, 2)} of state tax. Renting a car adds a ${h.rate(car)} leased vehicle gross receipts tax and a $2 daily surcharge on top of GRT. Feminine hygiene products have been deductible since July 1, 2022.</p>`,
  property: (h) => `<p>County assessors set each property's current and correct value as of January 1, and the constitution limits the taxable share to 33 1/3% of it: a home valued at ${h.usd(value)} is taxed on about ${h.usd(value / 3)}, less any exemption, and the levies of the county, the municipality, the school district and other districts apply to that net figure. County treasurers send the bills. The Notice of Valuation arrives around April 1; an owner who disagrees has 30 days from the mailing to protest before a County Valuation Protests Board, which includes an appraiser from the state Property Tax Division.</p>
<p>The cap on residential value is what keeps long-held homes cheap. Under Section 7-36-21.2, the taxable value of a home cannot rise more than 3% over the prior year, or 6.1% over two years if that is higher, whatever the market does. The limit does not apply the first year a property is valued, nor to physical improvements, solar installations excepted. Owners must report changes in their property to the assessor by the last day of February.</p>
<p>At the Census ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(350000)} house pays about ${h.usd(ptx('new-mexico', 350000))} a year. Owners aged 65 or older or disabled, with modified gross income up to $42,900 under the 2025 order, can have the value of their single-family home frozen. Resident veterans can exempt up to $10,000 of taxable value, and a 100% service-connected disabled veteran's main home can be fully exempt. Los Alamos, Santa Fe and Doña Ana counties also offer a rebate, claimed on form PIT-RC with the state income tax return, for incomes up to $24,000.</p>`,
  faqs: [
    { q: 'Do services get taxed in New Mexico?', a: `Yes, most of them. New Mexico's gross receipts tax applies to receipts from services as well as from goods, so repairs, professional fees and many personal services carry the ${rate(S.stateRate)} state rate plus the local increment. On a ${usd(500)} repair bill, the state part is ${usd(repair.stateTax, 2)}. The business owes the tax and usually passes it on as a separate line on the invoice.` },
    { q: `When is the New Mexico tax-free weekend in 2026?`, a: `${hol ? `From ${dayShort(hol.start)} to ${day(hol.end)}` : 'On the last weekend of July'}, from 12:01 a.m. on the last Friday in July to midnight on Sunday. Clothing and shoes under $100 an item, computers and e-readers up to $1,000, computer peripherals up to $500 and school supplies under $30 are free of gross receipts tax, with backpacks under $100 and calculators under $200 also included.` },
    { q: 'How much can New Mexico property taxes go up on a house?', a: `The taxable value of a residential property can rise by no more than 3% over the prior year, or 6.1% over two years if that is higher, under Section 7-36-21.2. The cap does not apply in the first year a property is valued or to physical improvements, other than solar installations. Owners 65 or older or disabled with low income can have the value frozen instead.` },
  ],
  related: ['arizona', 'texas', 'colorado', 'oklahoma', 'sales-tax-holidays', 'property-tax-assessment-caps'],
});
