import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank } from '../../lib/kit';

const s = st('new-jersey');
const S = s.sales, C = s.census, HS = s.property.homestead;
const uez = S.otherRates?.[0]?.rate ?? 0;
const occ = S.otherRates?.[3]?.rate ?? 0;
const anchor = HS.amount ?? 0;
const sofa = tx('new-jersey', 2400);
const sofaUez = (2400 * uez) / 100;
const jacket = tx('new-jersey', 400, 'clothing');
const billRank = rank(s, (x) => x.census.medianTax);
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'new-jersey',
  title: `New Jersey Property Tax 2026: ${usd(C.medianTax)} Median, ANCHOR, Stay NJ`,
  description: `New Jersey in 2026: ${rate(S.stateRate)} sales tax with no local add-on, clothing exempt, half rate in UEZs, and the highest property tax bills, eased by ANCHOR and Stay NJ.`,
  intro: `One sales tax rate from Cape May to the Hudson, clothing that is never taxed, and property tax bills that lead the country.`,
  resume: `New Jersey's property tax is the heaviest in the United States by the median bill: owners paid ${usd(C.medianTax)} in 2024 on a median home of ${usd(C.medianValue)} (Census ACS), ranked ${billRank} of 51, with an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank}. The state answers with benefit checks rather than an exemption on the bill: ANCHOR pays homeowners up to ${usd(anchor)}, and Stay NJ adds up to $6,500 for owners aged 65 and over. Sales tax is simpler than in its neighbors. A single ${rate(S.stateRate)} rate applies statewide, with no county or city sales tax, and clothing and footwear are exempt with no price limit. Most groceries are exempt too, though candy, soft drinks and prepared food are taxed. Shoppers pay half the rate, ${rate(uez)}, at certified stores in Urban Enterprise Zones and on many in-person purchases in Salem County, while Atlantic City and the Wildwoods add their own tourism taxes.`,
  sales: (h) => `<p>Because no county or town in New Jersey levies a general sales tax, the ${h.rate(S.stateRate)} on the receipt is the same in Newark and in a shore town, and the calculator above needs no local rate for ordinary goods. The rate has been ${h.rate(S.stateRate)} since January 1, 2018, after 7% from 2006 and 6.875% during 2017. A ${h.usd(2400)} sofa carries ${h.usd(sofa.stateTax, 2)} of tax.</p>
<p>The exceptions push the rate down more often than up. Businesses certified in an Urban Enterprise Zone charge half the rate, ${h.rate(uez)}, on most goods ordered in person in the zone, which brings the same sofa down to ${h.usd(sofaUez, 2)}; cars and energy are left out. Salem County gives the same half rate on qualifying in-person retail sales, but not on vehicles, alcohol, cigarettes, online orders, services, prepared food, lodging or cannabis. Upward, Atlantic City adds a 9% Luxury Tax (3% on drinks sold by the glass), with the combined total held to 12.625%, and Wildwood, Wildwood Crest and North Wildwood levy the Cape May County Tourism Sales Tax. Hotels add a ${h.rate(occ)} State Occupancy Fee in most towns, a possible municipal occupancy tax, and, since January 1, 2026, a $3 a day surcharge in Newark.</p>
<p>The exemptions are generous on everyday items. Clothing and footwear have no cap: a ${h.usd(400)} winter jacket owes ${h.usd(jacket.stateTax, 2)}, though fur, accessories and sports gear are taxed. Household paper towels, napkins, toilet tissue and paper plates are exempt, and SNAP purchases are never taxed. Electric cars lost their break: zero emission vehicles have paid the full rate since July 1, 2025. Online purchases taxed below ${h.rate(S.stateRate)} owe use tax, which residents can report on the NJ-1040 from a table based on income.</p>`,
  property: (h) => `<p>Municipal tax assessors value homes at true value as of October 1 of the year before the tax year, and the municipality collects for itself, the county and the school districts; there is no state property tax levy. Towns revalue at different times, so the state publishes an equalization table every year. On appeal, an assessment is tested against the district's average ratio with a common level range of plus or minus 15%. Appeals go to the County Board of Taxation by April 1 (May 1 after a revaluation, January 15 in Burlington, Gloucester and Monmouth counties), and assessments over $1 million can go straight to the Tax Court.</p>
<p>At the Census ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(500000)} house pays about ${h.usd(ptx('new-jersey', 500000))} a year. Relief arrives as payments. For the 2025 ANCHOR year, homeowners with income up to $150,000 receive ${h.usd(anchor)}, and those between $150,001 and $250,000 receive $1,000; renters get $450, or $700 at 65 and over. Many applicants under 65 are filed automatically, and the deadline is November 2, 2026. Stay NJ is reserved for owners 65 and over who lived in the home all of 2025 with income up to $200,000: up to $6,500, paid in February and May 2027, applied for on Form PAS-1 together with the Senior Freeze, which reimburses increases over a base year.</p>
<p>The local bill also carries a $250 deduction for eligible seniors and disabled owners, a $250 veteran deduction and a full exemption for 100% disabled veterans. All these benefits together cannot exceed the property tax actually paid on the main home for the year.</p>`,
  faqs: [
    { q: 'Is clothing taxed in New Jersey?', a: `No. New Jersey exempts clothing and footwear for human use from its ${rate(S.stateRate)} sales tax with no price cap, so a designer coat is as tax free as a pair of socks. Fur clothing, accessories, sport and recreational equipment and most protective equipment remain taxable. No county or town can add a local tax on clothing, because New Jersey has no general local sales tax.` },
    { q: 'How much is the New Jersey ANCHOR benefit for homeowners?', a: `For the 2025 ANCHOR year, homeowners with income of $150,000 or less receive ${usd(anchor)}, and those with income from $150,001 to $250,000 receive $1,000. Renters with income up to $150,000 get $450, or $700 if they are 65 or older. The application deadline is November 2, 2026, and many homeowners under 65 are filed automatically by the Division of Taxation.` },
    { q: 'What is the sales tax rate in a New Jersey Urban Enterprise Zone?', a: `Half the regular rate: ${rate(uez)} instead of ${rate(S.stateRate)}, on most taxable goods sold by businesses certified in the zone, when the order is placed in person there. Motor vehicles and energy do not get the reduced rate. The program is run by the Department of Community Affairs' UEZ Authority, and the store must hold the certification for the half rate to apply.` },
    { q: 'When is the deadline to appeal a property assessment in New Jersey?', a: `File with your County Board of Taxation by April 1 of the tax year, or by May 1 if your town completed a revaluation. Burlington, Gloucester and Monmouth counties use January 15. If the assessed value is above $1 million, you can file directly with the Tax Court. The appeal compares your assessment with the district's average ratio, within a range of plus or minus 15%.` },
  ],
  related: ['new-york', 'pennsylvania', 'delaware', 'clothing-sales-tax-by-state', 'property-tax-by-state'],
});
