import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, ptx, rank } from '../../lib/kit';

const s = st('new-hampshire');
const S = s.sales, C = s.census;
const meals = S.otherRates?.[0]?.rate ?? 0;
const phone = S.otherRates?.[3]?.rate ?? 0;
const dinner = 120, room = 220, nights = 3, plan = 90;
const billRank = rank(s, (x) => x.census.medianTax);
const effRank = rank(s, (x) => x.census.effectiveRate);
const house = 450000;

export default defineState({
  slug: 'new-hampshire',
  title: `New Hampshire Sales Tax 2026: None Statewide, ${rate(meals)} Meals Tax`,
  description: `New Hampshire sales tax in 2026: none on goods, but an ${rate(meals)} Meals and Rooms Tax on restaurants, hotels and car rentals. Property tax: median bill ${usd(C.medianTax)}.`,
  intro: `Nothing is added at the store counter, a tax on meals and rooms stands in for it, and towns carry the rest on the property tax bill.`,
  resume: `New Hampshire has no general sales tax and no use tax: furniture, electronics, clothing and groceries are sold at the ticket price, and no city or town adds a local sales tax. The tax that takes its place is the ${rate(meals)} Meals and Rooms (Rentals) Tax, charged on restaurant meals of $0.36 or more, on hotel rooms and short-term rentals, and on motor vehicle rentals; booking platforms must collect it like any innkeeper. Two-way communications services carry a separate ${rate(phone)} tax. The weight shifts to property: with no sales or income tax, municipalities assess, levy and collect property tax for the town, the county and the schools. The median owner paid ${usd(C.medianTax)} in 2024 on a home worth ${usd(C.medianValue)} (Census ACS), which ranks ${billRank} of 51 for the size of the bill and ${effRank} of 51 for the effective rate of ${eff(C.effectiveRate)}. There is no general homestead exemption; income-tested relief is claimed from the Department of Revenue Administration.`,
  sales: (h) => `<p>For a buyer, the absence of a sales tax in New Hampshire is total. The Department of Revenue Administration lists no sales tax, no use tax and no local sales or meals tax among the state's taxes, so a ${h.usd(2000)} refrigerator costs ${h.usd(2000)} at the register and nothing is owed later on an online order shipped to a New Hampshire address. There is no tax holiday because there is nothing to suspend.</p>
<p>The money comes from a tax on hospitality. At ${h.rate(meals)}, the Meals and Rooms (Rentals) Tax applies to food served by restaurants and other meal sellers, to hotel rooms and any place with sleeping accommodations, and to car rentals. A ${h.usd(dinner)} dinner for two adds ${h.usd(dinner * meals / 100, 2)}; three nights in a ${h.usd(room)} room add ${h.usd(room * nights * meals / 100, 2)}. The tax only starts at $0.36, and the bakery rule is a local curiosity: from a bakery that also acts as a restaurant, baked goods bought by the half dozen or more stay untaxed, while fewer than six count as a meal. Groceries bought to cook at home are never covered.</p>
<p>Short-term rental platforms and car-sharing sites count as operators, hold a Meals and Rentals license and collect the tax for their hosts. The rate has been ${h.rate(meals)} for periods beginning October 1, 2021. Separately, a ${h.rate(phone)} Communications Services Tax is added to two-way phone and data bills, so a ${h.usd(plan)} monthly plan carries ${h.usd(plan * phone / 100, 2)}. Visitors from Massachusetts or Maine who shop here should check their own state's use tax rules, since New Hampshire will not collect anything at the counter.</p>`,
  property: (h) => `<p>Property tax in New Hampshire is a town affair from start to finish. Local assessors value each home, and the municipality sets one tax rate that bundles the town, county and school shares and the State Education Property Tax, known as SWEPT. That last piece is set at a uniform state rate but still billed and collected by the town. Because towns revalue on different schedules, the Department of Revenue Administration runs equalization and ratio studies every year to compute each municipality's total equalized value, which is used to apportion county taxes, cooperative school taxes and the education tax.</p>
<p>At the Census median ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(house)} house pays about ${h.usd(ptx('new-hampshire', house))} a year. The DRA publishes the municipal, village district and education tax rates of every town each year, which is where to compare two towns before buying. Billing schedules are local, so the due dates are the ones printed on your town's bill.</p>
<p>There is no statewide homestead exemption. Relief takes two forms. Towns choose their own elderly, blind and disabled exemptions and veterans' tax credits, so the same retiree can get a different deduction in two adjacent towns. The state's Low and Moderate Income Homeowners Property Tax Relief refunds part of the State Education Property Tax to owners who lived in the home on April 1 with household income of $37,000 or less (single) or $47,000 or less (married or head of household), claimed on Form DP-8 or Granite Tax Connect between May 1 and June 30. An owner who thinks the assessment is wrong asks the local assessors for an abatement first, then appeals to the Board of Tax and Land Appeals or Superior Court.</p>`,
  faqs: [
    { q: 'Is there tax on restaurant food in New Hampshire?', a: `Yes. New Hampshire has no sales tax on goods, but restaurant meals costing $0.36 or more are subject to the ${rate(meals)} Meals and Rooms (Rentals) Tax, paid by the customer and remitted by the restaurant. On a ${usd(80)} meal that is ${usd(80 * meals / 100, 2)}. Groceries bought to eat at home are not taxed, and bakery items sold in quantities of six or more are not treated as meals.` },
    { q: 'Who qualifies for New Hampshire low and moderate income property tax relief?', a: `Homeowners subject to the State Education Property Tax who lived in the home on April 1 and whose household income is $37,000 or less for a single person, or $47,000 or less for a married couple or head of household. The claim is filed with the Department of Revenue Administration on Form DP-8 or Granite Tax Connect between May 1 and June 30 after the final tax bill.` },
    { q: 'Do I pay New Hampshire tax on a vacation rental booked online?', a: `Yes. Short-term rentals count as rooms under the ${rate(meals)} Meals and Rooms (Rentals) Tax, and booking platforms are treated as operators: they must hold a Meals and Rentals license and collect the tax on stays they arrange. Three nights at ${usd(room)} add ${usd(room * nights * meals / 100, 2)} in tax. The same rate applies to car rentals in New Hampshire.` },
  ],
  related: ['vermont', 'maine', 'massachusetts', 'states-without-sales-tax', 'homestead-exemption-by-state'],
});
