import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank } from '../../lib/kit';

const s = st('north-carolina');
const S = s.sales, C = s.census, HS = s.property.homestead;
const boat = S.otherRates?.[0]?.rate ?? 0;
const food = S.otherRates?.[3]?.rate ?? 0;
const excl = HS.amount ?? 0;
const cart = tx('north-carolina', 180, 'groceries', food);
const snacks = tx('north-carolina', 180, 'general', 2);
const boatTax = (p: number) => Math.min((p * boat) / 100, 1500);
const home = 300000;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'north-carolina',
  title: `North Carolina Sales Tax 2026: ${rate(S.stateRate)} State, ${rate(food)} on Food`,
  description: `North Carolina sales tax in 2026: ${rate(S.stateRate)} state rate, county taxes everywhere, flat ${rate(food)} local tax on groceries, $1,500 cap on boats, ${usd(C.medianTax)} median property tax.`,
  intro: `Every county adds tax, groceries are not quite tax free, and a property tax bill you can work out yourself from two numbers.`,
  resume: `North Carolina's state sales tax is ${rate(S.stateRate)}, but nobody pays it alone: all 100 counties levy local taxes totalling 2.00%, 48 of them add a 0.25% quarter-cent, and Durham, Mecklenburg, Orange and Wake add a 0.50% transit tax. Groceries are exempt from the state and transit rates but still pay a flat ${rate(food)} local rate in every county, while candy, soft drinks and prepared food are taxed in full. Clothing is taxed, and no sales tax holiday appears in the Department of Revenue's 2026 bulletins. Boats pay a reduced ${rate(boat)} with a $1,500 ceiling. Property tax is moderate: the median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51. Owners 65 or older or disabled with income up to $38,800 can exclude the greater of ${usd(excl)} or half the home's value by filing Form AV-9 by June 1.`,
  sales: (h) => `<p>The North Carolina Department of Revenue publishes one table of total rates by county, effective July 1, 2026, and it is the only lookup there is: no address tool exists, because local sales taxes are levied county-wide. The base pieces come from Articles 39, 40 and 42, which every county levies; Article 46 adds a quarter point in 48 counties, and Article 43 transit taxes apply in four. Mecklenburg County began an additional local tax on July 1, 2026, so receipts from before and after that date differ. A ${h.usd(180)} order of taxable goods in a county at the 2.00% base pays ${h.usd(snacks.tax, 2)} in total.</p>
<p>Food is the rule that surprises visitors. Qualifying groceries escape the ${h.rate(S.stateRate)} state rate and any transit tax, but a ${h.rate(food)} local rate applies everywhere, so a ${h.usd(180)} cart of groceries still carries ${h.usd(cart.tax, 2)} of tax. Candy, soft drinks, dietary supplements and vending machine food are non-qualifying and pay full rates, and so does prepared food, defined as food sold heated, two or more foods combined by the store, or food sold with utensils the store provides.</p>
<p>Some big-ticket items are taxed on their own terms. Boats, jet skis, kayaks and canoes pay ${h.rate(boat)} with a maximum of $1,500 and no local rate: ${h.usd(boatTax(30000))} on a ${h.usd(30000)} boat, and the cap is reached at ${h.usd(1500 / boat * 100)}. Surfboards and paddle boards are not boats and pay the general rate. Manufactured and modular homes are taxed at ${h.rate(S.stateRate)} on half the price, aircraft at the state rate with a $2,500 maximum. Cars pay a highway use tax collected by NCDMV, not sales tax. Items bought out of state without tax owe use tax, reported on Form D-400 by individuals.</p>`,
  property: (h) => `<p>North Carolina publishes the formula for a property tax bill, and it fits on one line: the county's appraisal divided by 100, times the combined county and city or district rate per $100. The Department of Revenue's own example is a ${h.usd(200000)} home at a combined 0.865 per $100, which owes $1,730. The appraisal is the market value as of the county's last reappraisal, not today's price, and reappraisal years vary by county, so two similar houses in neighboring counties can be valued years apart.</p>
<p>At the Census median ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(home)} house pays about ${h.usd(ptx('north-carolina', home))} a year. Property is listed in January, in the county where it sits, and counties may extend the listing period. Cars are handled differently: under Tag and Tax Together, the vehicle property tax is paid to NCDMV with the registration renewal.</p>
<p>Three relief programs apply to a permanent residence, filed together on Form AV-9 with the county assessor by June 1. The Elderly or Disabled Homestead Exclusion removes the greater of ${h.usd(excl)} or 50% of the appraised value for owners aged 65 or older, or totally and permanently disabled, with prior-year income up to $38,800 for 2026 ($39,900 for 2027): on a ${h.usd(home)} home that is ${h.usd(Math.max(excl, home / 2))} off the taxable value. The Circuit Breaker deferment limits taxes to 4% or 5% of income for owners who have lived in the home five full years, deferring the rest. Disabled veterans can exclude up to $45,000 of value with no age or income test.</p>`,
  faqs: [
    { q: 'Do you pay tax on groceries in North Carolina?', a: `Yes, but less than on other goods. Qualifying food is exempt from the ${rate(S.stateRate)} state rate and from transit taxes, yet every county charges a flat ${rate(food)} local rate on it, so ${usd(100)} of groceries costs ${usd(tx('north-carolina', 100, 'groceries', food).tax, 2)} in tax. Candy, soft drinks, dietary supplements, vending machine food and prepared food are not qualifying food and pay the full state, county and transit rates.` },
    { q: 'What is the sales tax on a boat in North Carolina?', a: `Boats are taxed at a state rate of ${rate(boat)}, with a maximum of $1,500 per boat, and no county or transit tax is added. The rule covers jet skis, kayaks and canoes. On a ${usd(30000)} boat the tax is ${usd(boatTax(30000))}; any boat over ${usd(1500 / boat * 100)} pays the $1,500 cap. Surfboards, paddle boards and windsurfers do not count as boats and pay the general combined rate.` },
    { q: 'Who qualifies for the North Carolina homestead exclusion?', a: `Owners of a permanent residence who are 65 or older, or totally and permanently disabled, with prior-year income of $38,800 or less for the 2026 tax year. The exclusion removes the greater of ${usd(excl)} or half of the home's appraised value. File Form AV-9 with your county assessor by June 1. Disabled veterans have a separate exclusion of up to $45,000 with no income limit.` },
  ],
  related: ['south-carolina', 'virginia', 'tennessee', 'georgia', 'grocery-sales-tax-by-state', 'how-property-tax-is-calculated'],
});
