import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank, day, dayShort } from '../../lib/kit';

const s = st('ohio');
const S = s.sales, C = s.census, PR = s.property, HS = s.property.homestead;
const cap = S.local.cap ?? 0;
const hol = S.holidays2026?.[0];
const ratio = PR.assessment?.ratio ?? 0;
const hs = HS.amount ?? 0;
const jeans = tx('ohio', 70);
const coat = tx('ohio', 180);
const home = 250000;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'ohio',
  title: `Ohio Sales Tax 2026: ${rate(S.stateRate)} Rate, 8.75% Cap, August Holiday`,
  description: `Ohio sales tax in 2026: ${rate(S.stateRate)} state rate plus county and transit taxes up to ${rate(cap)}, an August back-to-school holiday and a ${usd(hs)} homestead exemption for seniors.`,
  intro: `A state rate unchanged since 2013, county and transit add-ons with a hard ceiling, and a property tax system built on 35% of value and reduction factors.`,
  resume: `Ohio's state sales tax has been ${rate(S.stateRate)} since September 1, 2013. Counties and regional transit authorities add permissive taxes in steps of 0.05%, up to ${rate(cap)} together, and the combined rate can never pass 8.75%, so the rate at the register depends on the county where the sale is sourced. Food bought to eat at home has been exempt since a 1936 constitutional amendment; restaurant meals, soft drinks and alcohol are taxed. Clothing is taxed except during the back-to-school holiday${hol ? `, ${dayShort(hol.start)} to ${day(hol.end)}` : ''}, when items of $75 or less are tax free. On property, the median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51. Owners 65 or older, or disabled, with income up to $41,000 get a credit equal to the taxes on ${usd(hs)} of value, and their county may now double it.`,
  sales: (h) => `<p>Ohio's local layer is county-wide. A county may levy a permissive sales tax and a regional transit authority may levy another, each set in multiples of 0.05%, and the two together cannot take the total above 8.75%. Changes can only start on the first day of a calendar quarter; in 2026, Warren County's rate changed on October 1 and no other county moved. The Department of Taxation's Finder returns the rate for an address, which you then enter as the local part above.</p>
<p>The back-to-school holiday is permanent, written into law since 2018 for the first Friday of August and the following weekend. ${hol ? `In 2026 it runs from ${h.day(hol.start).replace(', 2026', '')} to ${h.day(hol.end)}.` : ''} Clothing priced at $75 or less per item, school supplies at $20 or less and instructional materials at $20 or less are sold tax free. The limit works item by item: a pair of jeans at ${h.usd(70)} saves ${h.usd(jeans.stateTax, 2)} of state tax, but a ${h.usd(180)} coat bought the same day pays the full rate, ${h.usd(coat.stateTax, 2)} at the state level. The broader holiday on items up to $500 that H.B. 33 created was not repeated in 2026.</p>
<p>Exemptions worth knowing include prescription glasses and contact lenses since July 1, 2019, and pads, tampons and period underwear since April 1, 2020. Prepared food, dietary supplements and tobacco stay taxable. A car bought from a private seller still owes sales or use tax, paid to the county clerk of courts when the title is transferred. Online or out-of-state purchases on which no tax was collected owe use tax at the same state and county rate.</p>`,
  property: (h) => `<p>Ohio has no state property tax. School districts, counties, cities, townships and special districts levy it, and the 88 county auditors set values: a full reappraisal every six years and an update at the three-year mark. Tax is charged on ${h.num(ratio)}% of true market value, so a ${h.usd(home)} house carries a taxable value of ${h.usd(home * ratio / 100)}. The constitution limits unvoted, or inside, millage to 10 mills, which works out to 0.35% of true value; everything above that is voted by residents as levies.</p>
<p>The feature that makes Ohio bills hard to predict from values alone is the tax reduction factor from H.B. 920. When a reappraisal raises values, reduction factors offset that growth on voted levies, so the effective millage ends up below the voted figure: the statewide average in 2024 was about 52.44 effective mills on homes and farms, against 66.69 on commercial and industrial property. At the Census ratio of ${h.eff(C.effectiveRate)}, the ${h.usd(home)} house pays about ${h.usd(ptx('ohio', home))} a year. Homes also get a 10% non-business credit and a 2.5% owner-occupancy credit, but neither applies to levies passed after September 29, 2013.</p>
<p>The Homestead Exemption for owners 65 or older, totally and permanently disabled, or qualifying surviving spouses is a credit equal to the taxes on ${h.usd(hs)} of market value in 2026, about ${h.usd(ptx('ohio', hs))} at the typical rate, with Ohio modified AGI of $41,000 or less. Disabled veterans get $59,400 with no income test. File form DTE 105A with the county auditor by December 31; it then renews on its own. H.B. 96 lets county commissioners add a local homestead exemption equal to the state one. Bills come in two halves, usually around February and July, and value complaints go to the county Board of Revision between January 1 and March 31.</p>`,
  faqs: [
    { q: `What qualifies for Ohio's 2026 sales tax holiday?`, a: `${hol ? `From ${dayShort(hol.start)} to ${day(hol.end)}` : 'On the first weekend of August'}, clothing priced at $75 or less per item, school supplies at $20 or less and school instructional materials at $20 or less are free of Ohio sales tax, normally ${rate(S.stateRate)} plus the county rate. An item priced above its limit is taxed as usual. The larger holiday on items up to $500 was not held again in 2026.` },
    { q: 'How much does the Ohio homestead exemption save?', a: `It is a credit equal to the taxes on ${usd(hs)} of market value for tax year 2026, so the saving follows your local millage; at Ohio's typical effective rate that is about ${usd(ptx('ohio', hs))} a year. It is for owners 65 or older or disabled with income up to $41,000. Disabled veterans get the taxes on $59,400. If your county adopts the H.B. 96 option, the exemption can double.` },
    { q: 'What is the highest sales tax rate allowed in Ohio?', a: `8.75%. Ohio's state rate is ${rate(S.stateRate)}, and counties and regional transit authorities may add permissive sales taxes in steps of 0.05% up to ${rate(cap)} in total, but state, county and transit rates combined cannot exceed 8.75%. Local changes start only at the beginning of a calendar quarter. The Department of Taxation's Finder gives the rate for any Ohio address.` },
  ],
  related: ['pennsylvania', 'michigan', 'indiana', 'kentucky', 'sales-tax-holidays', 'homestead-exemption-by-state'],
});
