import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank, day, dayShort } from '../../lib/kit';

const s = st('oklahoma');
const S = s.sales, C = s.census, HS = s.property.homestead;
const hol = S.holidays2026?.[0];
const hx = HS.amount ?? 0;
const carRate = S.otherRates?.[0]?.rate ?? 0;
const cart = tx('oklahoma', 200);
const boots = tx('oklahoma', 95);
const truck = 40000;
const home = 220000;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'oklahoma',
  title: `Oklahoma Sales Tax 2026: ${rate(S.stateRate)} State, 0% on Groceries`,
  description: `Oklahoma sales tax in 2026: ${rate(S.stateRate)} state rate, 0% state tax on groceries but local taxes still due, an August clothing holiday, and a ${usd(C.medianTax)} median property tax.`,
  intro: `The state stopped taxing groceries in 2024, the cities and counties did not, and property values for homeowners can rise only 3% a year.`,
  resume: `Oklahoma's state sales tax is ${rate(S.stateRate)}, and counties and incorporated cities and towns add voter-approved local taxes at the point of delivery, so the total on a receipt depends on the delivery address. Since August 29, 2024, grocery food has carried a 0% state rate, but city and county sales taxes still apply to it, and prepared food, deli sandwiches, rotisserie chicken, pet food, vitamins and over-the-counter medicine stay taxable at ${rate(S.stateRate)}. Clothing and footwear under $100 are exempt from the state portion during the August back-to-school weekend. New cars pay a ${rate(carRate)} excise tax instead of local sales tax. Property tax is low: the median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51, with homes assessed at 11% to 13.5% of value and a 3% yearly cap on homestead values.`,
  sales: (h) => `<p>Two numbers make up every Oklahoma receipt: the ${h.rate(S.stateRate)} state rate, and a local rate that combines what the county and the city or town charge where the goods are delivered. A general county sales tax cannot exceed 2% and needs voter approval, but other statutes allow more county levies and cities set their own rates, so no overall ceiling exists. The Tax Commission links to the University of Oklahoma's rate locator for the exact combined figure; type its local part into the calculator above.</p>
<p>The grocery change of 2024 (HB 1955 and SB 1283) removed only the state's share. A ${h.usd(200)} grocery run that paid ${h.usd(cart.stateTax, 2)} of state tax before August 29, 2024 now pays none to the state, yet the local rate is still charged on the full amount, so choose "Groceries" in the calculator and enter your local rate to see what remains. The line between food and non-food is drawn tightly: fountain drinks, rotisserie chicken and deli sandwiches stay taxed, and a store whose prepared food exceeds 75% of its food sales, with utensils available, must charge state tax on all its food.</p>
<p>The back-to-school holiday${hol ? `, ${dayShort(hol.start)} to ${h.day(hol.end)},` : ''} follows the statute's first-Friday-of-August rule and covers clothing and footwear priced under $100, not athletic gear, accessories or rentals. It removes only the state's ${h.rate(S.stateRate)}: a ${h.usd(95)} pair of boots saves ${h.usd(boots.stateTax, 2)}, while local tax is still charged. Vehicles follow their own rule: a new ${h.usd(truck)} truck pays the ${h.rate(carRate)} motor vehicle excise tax, ${h.usd(truck * carRate / 100)}, plus a 1.25% portion of state sales tax, and no city or county tax. Veterans with a 100% service-connected disability can get a permit exempting up to $25,000 of purchases a year.</p>`,
  property: (h) => `<p>County assessors value homes at fair cash value and then apply an assessment percentage chosen by each county between 11% and 13.5%, the range set by the State Board of Equalization. A ${h.usd(home)} house is therefore assessed at roughly ${h.usd(home * 0.11)} to ${h.usd(home * 0.135)}, and the levies of the county, school district, city and other districts apply to that figure. Under the state constitution, the fair cash value of a homestead or farmland cannot rise more than 3% a year, and other property 5%, unless the property is sold or improved. A long-held home can thus be valued well below its market price.</p>
<p>At the Census ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(home)} home pays about ${h.usd(ptx('oklahoma', home))} a year. The homestead exemption removes ${h.usd(hx)} of assessed value, which at an 11% to 13.5% assessment level is the tax on about ${h.usd(hx / 0.135)} to ${h.usd(hx / 0.11)} of market value. Heads of household with gross household income of $30,000 or less get another ${h.usd(hx)} through Form 994. Apply to the county assessor on OTC Form 921 by March 15, or within 30 days of a notice of a higher valuation; the exemption then carries over while you live in the home, but it is cancelled if you have delinquent personal property taxes.</p>
<p>Owners 65 and older with income under their county's HUD-based limit, $99,000 in Cleveland County for 2026, can freeze the home's value. Veterans rated 100% permanently disabled are fully exempt on the homestead, and so are their surviving spouses. Taxes are due November 1; paying at least half before January 1 lets you pay the rest before April 1, otherwise the whole bill is late on January 1 and draws 1.5% interest a month.</p>`,
  faqs: [
    { q: 'Is there still sales tax on groceries in Oklahoma?', a: `Only the local part. Since August 29, 2024, food and food ingredients carry a 0% Oklahoma state rate instead of ${rate(S.stateRate)}, but city and county sales taxes still apply to them. Prepared food, rotisserie chicken, deli sandwiches, fountain drinks, pet food, vitamins, alcohol and over-the-counter medicine remain taxable at the full state rate plus the local rate.` },
    { q: 'How do I file for the Oklahoma homestead exemption?', a: `File OTC Form 921 with your county assessor by March 15, or within 30 days of receiving a notice that your valuation went up. The exemption takes ${usd(hx)} of assessed value off your owner-occupied home, and you do not need to reapply while you keep living there. If your gross household income is $30,000 or less, file Form 994 for an additional ${usd(hx)}.` },
    { q: 'Does Oklahoma charge local sales tax on a new car?', a: `No. A new vehicle bought in Oklahoma pays a ${rate(carRate)} motor vehicle excise tax on its value plus a 1.25% portion of state sales tax, and city and county sales taxes do not apply. On a ${usd(truck)} new truck the excise tax alone is ${usd(truck * carRate / 100)}. Used vehicles follow a different excise schedule.` },
  ],
  related: ['texas', 'kansas', 'arkansas', 'missouri', 'grocery-sales-tax-by-state', 'property-tax-assessment-caps'],
});
