import { defineState } from '../../lib/page-types';
import { st, usd, rate, eff, tx, ptx, rank } from '../../lib/kit';

const s = st('pennsylvania');
const S = s.sales, C = s.census;
const allegheny = 1, philly = 2;
const lease = S.otherRates?.[1]?.rate ?? 0;
const rental = S.otherRates?.[2]?.rate ?? 0;
const tv = (local: number) => tx('pennsylvania', 1200, 'general', local);
const suit = tx('pennsylvania', 400);
const home = 280000;
const effRank = rank(s, (x) => x.census.effectiveRate);

export default defineState({
  slug: 'pennsylvania',
  title: `Pennsylvania Sales Tax 2026: ${rate(S.stateRate)} State, ${rate(S.stateRate + philly)} in Philadelphia`,
  description: `Pennsylvania sales tax in 2026: ${rate(S.stateRate)} statewide, ${rate(S.stateRate + allegheny)} in Allegheny County, ${rate(S.stateRate + philly)} in Philadelphia; clothing, groceries and candy exempt. Property tax median ${usd(C.medianTax)}.`,
  intro: `One state rate, two places that add to it by law, and a list of exemptions that covers most clothing and even candy.`,
  resume: `Pennsylvania charges a ${rate(S.stateRate)} sales tax, and only two places add a local tax: Allegheny County, which brings the total to ${rate(S.stateRate + allegheny)}, and the City of Philadelphia, at ${rate(S.stateRate + philly)}. Everywhere else, ${rate(S.stateRate)} is the full rate. The exemptions are broad: grocery food, candy and gum, most clothing whatever its price, textbooks, residential heating fuels and prescription drugs are all untaxed, while restaurant meals, formal wear, sporting clothing, fur and digital products such as downloaded software are taxed. There is no sales tax holiday. Property tax is levied only locally, by counties, municipalities and school districts. The median owner paid ${usd(C.medianTax)} in 2024 on a ${usd(C.medianValue)} home (Census ACS), an effective rate of ${eff(C.effectiveRate)}, ranked ${effRank} of 51. Relief comes from the Act 1 homestead exclusion on school taxes, funded by gaming revenue, and the Property Tax/Rent Rebate of up to $1,000 for older and disabled residents.`,
  sales: (h) => `<p>Pennsylvania settled the local question by statute: counties and Philadelphia may levy a local sales tax at a rate fixed in the law, and only Allegheny County (1%) and Philadelphia (2%) do so. A ${h.usd(1200)} television costs ${h.usd(tv(0).tax, 2)} in tax in most of the state, ${h.usd(tv(allegheny).tax, 2)} in Allegheny County and ${h.usd(tv(philly).tax, 2)} in Philadelphia. Use tax follows the same pattern: items delivered to or used in those two places owe the local part too, and individuals can report use tax on the PA-40.</p>
<p>The clothing rule is the one shoppers should learn. Most clothing is exempt with no price cap, so an expensive winter coat is untaxed, but the law singles out formal day or evening apparel, bridal wear, fur articles, sporting clothing, accessories and ornamental wear as taxable: a ${h.usd(400)} tuxedo or gown carries ${h.usd(suit.stateTax, 2)} of state tax. Food follows a similar logic. Groceries that are not ready to eat are exempt, and so are candy and gum, but ready-to-eat food from restaurants and caterers is taxed. Heating oil, gas, electricity, coal and firewood for a home are exempt; canned software and other digital goods are taxed.</p>
<p>Cars and rooms have their own charges. Hotel stays under 30 days pay the ${h.rate(S.stateRate)} hotel occupancy tax, plus the local 1% where it applies, including rooms booked through online brokers. A short-term car rental pays sales tax, a ${h.rate(rental)} Vehicle Rental Tax and a $2 daily Public Transportation Assistance fee; a lease of 30 days or more adds a ${h.rate(lease)} PTA tax to the payments. Each new tire carries a $1 fee.</p>`,
  property: (h) => `<p>Pennsylvania has no state property tax and no statewide assessment cycle. County assessment offices set values, and counties, municipalities and school districts each levy their own millage on them. At the Census ratio of ${h.eff(C.effectiveRate)}, a ${h.usd(home)} house pays about ${h.usd(ptx('pennsylvania', home))} a year. A sale adds the realty transfer tax: 1% to the state, often with a local transfer tax collected by the county Recorder of Deeds on top.</p>
<p>Act 1 of 2006 does two things for homeowners. It stops a school district from raising its tax faster than an annual inflation index without a voter referendum, unless an exception applies. And it created the homestead and farmstead exclusion, which lowers the assessed value of a primary residence for school taxes, paid for with state gaming revenue. The amount depends on the school district, so there is no single figure: the district must remind owners about it by December 31, and the application goes to the county assessment office by March 1. Reapplication cannot be required more than once every three years. Farm owners on at least 10 contiguous acres can add the farmstead exclusion for agricultural buildings. In Philadelphia, the same state money lowers the wage tax instead.</p>
<p>The Property Tax/Rent Rebate program pays $380 to $1,000 to homeowners and renters aged 65 or older, widows and widowers 50 or older, and people with disabilities, with household income of $48,110 or less. 2025 claims are accepted until December 31, 2026, and the rebate must be claimed again each year.</p>`,
  faqs: [
    { q: 'What is the sales tax in Philadelphia, Pennsylvania?', a: `${rate(S.stateRate + philly)}: Pennsylvania's ${rate(S.stateRate)} state sales tax plus a 2% local tax that the law sets for the City of Philadelphia. On a ${usd(1200)} purchase that is ${usd(tv(philly).tax, 2)}. Allegheny County pays ${rate(S.stateRate + allegheny)}, and every other county pays only the state ${rate(S.stateRate)}. Goods delivered to a Philadelphia address owe the 2% local part even when bought online.` },
    { q: 'Is formal wear taxed in Pennsylvania?', a: `Yes. Pennsylvania exempts most clothing from its ${rate(S.stateRate)} sales tax regardless of price, but formal day or evening apparel, bridal wear, fur articles, sporting clothing, accessories and ornamental wear are taxable. A ${usd(400)} tuxedo or evening gown carries ${usd(suit.stateTax, 2)} of state tax, more in Allegheny County or Philadelphia. Everyday clothing, coats and shoes stay untaxed all year, and the state holds no sales tax holiday.` },
    { q: 'Who qualifies for the Pennsylvania Property Tax/Rent Rebate?', a: `Homeowners and renters aged 65 or older, widows and widowers aged 50 or older, and people with disabilities aged 18 or older, with household income of $48,110 or less for 2025 claims. The standard rebate runs from $380 to $1,000, with supplemental amounts for some low-income homeowners. Claims for 2025 are accepted until December 31, 2026, and you must reapply every year.` },
  ],
  related: ['new-jersey', 'new-york', 'ohio', 'maryland', 'clothing-sales-tax-by-state', 'homestead-exemption-by-state'],
});
